## 5. <strong>NumPy 배열</strong>

In [4]:
# Python 패키지 설치 명령어
!pip install numpy

In [5]:
# NumPy 불러오기
import numpy as np

### <strong> 5.1 NumPy 배열 생성

In [5]:
# [+] 리스트 객체로부터 ndarray 객체 생성
my_lst = [1,2,3,4,5,6]
my_arr = np.array(my_lst)

my_arr

array([1, 2, 3, 4, 5, 6])

In [7]:
# [+] 리스트/NumPy 배열 동시에 생성
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

#### 리스트 컴프리헨션 vs NumPy 배열

In [9]:
prices = [20, 40, 35, 10, 25, 56]

# [+] 리스트 컴프리헨션을 이용하여 5달러씩 가격을 일괄적으로 할인하기
new_prices = [price-5 for price in prices]

new_prices

[15, 35, 30, 5, 20, 51]

In [11]:
# [+] NumPy 배열의 연산을 통한 5달러씩 가격을 일괄적으로 할인하기
prices_arr = np.array(prices)   # 배열 생성
prices_arr -= 5# 가격 수정

prices_arr

array([15, 35, 30,  5, 20, 51])

#### 예제: 시험 점수 처리

In [15]:
# 세 번의 시험에 대한 점수를 NumPy 배열로 선언
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

In [21]:
# [+] 세 번째 시험에 2점씩 더하기
test_3_fixed = test_3 + 2

test_3_fixed

array([89, 87, 74, 92, 94])

In [23]:
# [+] 학생 별 전체 시험 점수 총합 계산 -> total_grade
total_grade = test_1 + test_2 + test_3_fixed

total_grade

array([260, 281, 248, 276, 272])

In [25]:
# [+] 학생 별 평균 시험 점수 계산 -> final_grade
final_grade = total_grade / 3

final_grade

array([86.66666667, 93.66666667, 82.66666667, 92.        , 90.66666667])

In [27]:
# [+] 인덱싱: Jeremy의 두 번째 시험 점수
jeremy_test_2 = test_2[3]

jeremy_test_2

93

In [31]:
# [+] Manual과 Adwoa의 첫 번째 시험 점수
manual_adwoa_test_1 = test_1[1:3]

manual_adwoa_test_1

array([94, 88])

In [33]:
# [+] 전체 학생들의 점수를 2차원 배열에 저장 -> student_scores
student_scores = np.array([test_1, test_2, test_3_fixed])

student_scores

array([[ 92,  94,  88,  91,  87],
       [ 79, 100,  86,  93,  91],
       [ 89,  87,  74,  92,  94]])

In [39]:
# [+] 2차원 배열 인덱싱: Tanya의 세 번째 시험 점수
student_scores[2,0] #[2][0]

89

In [45]:
# [+] 2차원 배열 슬라이싱: Cody의 전체 시험 점수
student_scores[:,4]

array([87, 91, 94])

#### 배열 원소 단위의 논리 연산

In [47]:
a = np.array([1, 20, 4, 6, 28, 88, 7, 12])

# [+] 10 이상 여부를 마스킹
mask = a >= 10

mask

array([False,  True, False, False,  True,  True, False,  True])

In [49]:
# [+] 논리 연산을 이용하여 부분집합 구하기
selected = a[a >= 10]

selected

array([20, 28, 88, 12])

In [51]:
# [+] 논리식 결합: 논리합
selected = a[(a > 10) | (a < 8)]

selected

array([ 1, 20,  4,  6, 28, 88,  7, 12])

In [53]:
# [+] 논리식 결합: 논리곱
selected = a[(a > 10) & (a < 30)]

selected

array([20, 28, 12])

In [65]:
# [+] 정수 배열 생성
np.arange(10) # (stop) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
np.arange(10, 20) # (start, stop)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [71]:
np.arange(10, 20, 3) # (start, stop, interver)

array([10, 13, 16, 19])

In [15]:
# [+] 난수 배열 생성
np.random.seed(5)
arr = np.random.randint(10, size=(3,5))

arr

array([[3, 6, 6, 0, 9],
       [8, 4, 7, 0, 0],
       [7, 1, 5, 7, 0]])

### <strong>5.2 배열 조작 연산</strong>

In [27]:
# [+] 배열 속성
print(arr.ndim)     # 차원 수
print(arr.shape)    # 형상
print(arr.size)     # 크기
print(arr.dtype)    # 데이터 타입
print(arr.itemsize) # 원소별 메모리 크기(bytes)
print(arr.nbytes)   # 전체 메모리 크기

2
(3, 5)
15
int32
4
60


In [39]:
# [+] 배열 슬라이싱
arr = np.arange(10)
print(arr)

print(arr[3:7]) # 슬라이싱(start:stop)
print(arr[:5]) # 시작 인덱스 생략(:stop)
print(arr[5:]) # 종료 인덱스 생략(start:)
print(arr[::3]) # 간격(::interval)
print(arr[2:8:2]) # 슬라이싱(start:stop:interval)

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]
[0 1 2 3 4]
[5 6 7 8 9]
[0 3 6 9]
[2 4 6]


In [41]:
# [+] 난수 배열 생성
np.random.seed(0)  # [+] 시드 설정
arr = np.random.randint(10, size=(6, 8)) # [+] 난수 배열 생성

arr

array([[5, 0, 3, 3, 7, 9, 3, 5],
       [2, 4, 7, 6, 8, 8, 1, 6],
       [7, 7, 8, 1, 5, 9, 8, 9],
       [4, 3, 0, 3, 5, 0, 2, 3],
       [8, 1, 3, 3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7, 3, 2, 7]])

In [47]:
# [+] 다차원 배열 슬라이싱
arr[1:4, 4:]

array([[8, 8, 1, 6],
       [5, 9, 8, 9],
       [5, 0, 2, 3]])

In [51]:
# 배열 슬라이스 = 뷰(view)
arr_sub = arr[:2, :2]
print(arr_sub)

arr_sub[0, 0] = 99
print(arr_sub)

print(arr)

[[5 0]
 [2 4]]
[[99  0]
 [ 2  4]]
[[99  0  3  3  7  9  3  5]
 [ 2  4  7  6  8  8  1  6]
 [ 7  7  8  1  5  9  8  9]
 [ 4  3  0  3  5  0  2  3]
 [ 8  1  3  3  3  7  0  1]
 [ 9  9  0  4  7  3  2  7]]


In [53]:
# 배열 복사본 생성
arr_sub = arr[:2, :2].copy()

arr_sub[0, 0] = 50
print(arr_sub)

print(arr)

[[50  0]
 [ 2  4]]
[[99  0  3  3  7  9  3  5]
 [ 2  4  7  6  8  8  1  6]
 [ 7  7  8  1  5  9  8  9]
 [ 4  3  0  3  5  0  2  3]
 [ 8  1  3  3  3  7  0  1]
 [ 9  9  0  4  7  3  2  7]]


In [65]:
# [+] 배열 재구조화: reshape()
x = np.arange(10) # 0~9로 이루어진 배열 생성 (10,)
print(x)
print(x.shape)

x = x.reshape(2,5) # 배열을 2X5 형상으로 재구조화
print(x)
print(x.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)


In [74]:
np.array(1,4)
arr

TypeError: Cannot interpret '4' as a data type

In [76]:
# [+] 배열 재구조화: 차원 추가(np.newaxis)
arr_new = arr[:, np.newaxis]
print(arr_new)
print(arr_new.shape)

[[1]
 [2]
 [3]]
(3, 1)


#### <strong> 배열 연결하기</strong>

In [78]:
# 세 개의 배열 생성
arr_1 = np.arange(1, 4)
arr_2 = np.arange(4, 7)
arr_3 = np.arange(7, 10)

print(arr_1, arr_2, arr_3)

[1 2 3] [4 5 6] [7 8 9]


In [80]:
# [+] 배열 연결: np.concatenate()
np.concatenate([arr_1, arr_3, arr_2])

array([1, 2, 3, 7, 8, 9, 4, 5, 6])

In [82]:
# [+] 배열 연결: 종연결 
arr_total = np.vstack([arr_1, arr_2, arr_3])

arr_total

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
# [+] 배열 연결: 횡연결
arr_total = np.hstack([arr_1, arr_2, arr_3])

arr_total

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
arr = [1, 2, 3, 99, 99, 3, 2, 1]
print(arr)

# [+] 배열 분할 [1,2,3], [99,99], [3,2,1]
arr_1, arr_2, arr_3 = np.split(arr, [3,5])
print(arr_1, arr_2, arr_3)

[1, 2, 3, 99, 99, 3, 2, 1]
[1 2 3] [99 99] [3 2 1]
